version: '3.8'

name: go-ms-template

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: nanda # Replace with your desired username
      POSTGRES_PASSWORD: test # Replace with your desired password
      POSTGRES_DB: go-ms-template # Replace with your desired database name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-data:
